name: CI-pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: 'The Version You Wanna Deploy To Test Env (First 7 Github SHA)'
        required: true
        default: "latest"
env:
  DEPLOY_ENV: dev
  
jobs:
  CI_CD:
    runs-on: ubuntu-latest
    # --- log start time for build metrics
    outputs:
      start_time: ${{steps.build_start_time.outputs.start_time}}
    steps:
      - name: Log Build Start Time
        id: build_start_time
        run: echo "::set-output name=start_time::$(date +%s)"

      - name: Deploy to dev
        run: echo deployed
  post-workflow-status:
    if: always()
    name: Post Workflow Status
    needs:
      - CI_CD
    runs-on: ubuntu-latest
    steps:
      #--- Send events and metrics to Datadog ----
      - name: Send Metrics to Datadog
        uses: Tomoloyalty/datadog-metrics-action@master
        with:
          result: ${{ needs.CI_CD.result }}
          env-name: ${{ env.DEPLOY_ENV }}
          github-context: ${{ tojson(github) }}
          api-key: ${{ secrets.DATADOG_API_KEY }}
          start-timestamp: ${{ needs.CI_CD.outputs.start_time }}
